# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print current directory
#         run: pwd

#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "14"

#       - name: Install dependencies
#         run: npm install

#       - name: Install Cypress
#         run: npm install cypress

#       - name: Run Cypress tests
#         run: npm run cy:run -- --parallel --group ${{ github.workflow }} --ci-build-id ${{ github.run_id }}

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest

   strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Check for duplicated file names
        run: |
          git ls-files --exclude-standard --others --cached --no-empty-directory | sort -f > files.txt
          uniq -di files.txt > duplicates.txt
          if [[ -s duplicates.txt ]]; then
            echo "Found files with the same name:"
            cat duplicates.txt
            exit 1
          fi


- name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Npm install
        run: npm ci

- name: Npx run
        run: npx cypress run --headless