name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
- name: Checkout repository
  uses: actions/checkout@v3
  with:
    ref: main  # Or the branch containing your package.json file

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Print current directory
        run: pwd

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cy:run -- --record --parallel --group ${{ github.workflow }} --ci-build-id ${{ github.run_id }}
